"""Audit the glyphs actually served by @font-face and generate UI coverage data.

Run: python scripts/audit-fonts.py [--check] [--repair-optima]
Requires fonttools[woff] (FontTools and Brotli). The check mode never edits files.
"""

import argparse
import hashlib
import json
import logging
from pathlib import Path
import re
import unicodedata

from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "fontCoverageData.js"
OPTIMA_FILES = (
    "OPTIMA.TTF", "OPTIMA_0.TTF", "Optima.woff", "Optima.woff2",
    "Optima-Bold.woff", "Optima-Bold.woff2",
)
SAMPLES = {
    "customerWording": "Renée O'Connor\nDirector, R&D\nSt. Louis • 2026",
    "accents": "éèêëàáâäçñöøüßœ",
    "punctuationAndSymbols": "•’“”–—♥★∞",
    "hebrew": "שָׁלוֹם",
}


def ranges(codepoints):
    result = []
    for cp in sorted(codepoints):
        if result and cp == result[-1][1] + 1:
            result[-1][1] = cp
        else:
            result.append([cp, cp])
    return result


def invisible(cp):
    return chr(cp).isspace() or unicodedata.category(chr(cp)) in ("Cf", "Cc")


def repair_optima():
    """Remove untrustworthy legacy non-ASCII mappings; never invent outlines.

    These original fonts label Windows-1251 outlines as Latin-1. Even their
    bullet has no outline. Removing those mappings permits browser fallback.
    All visible ASCII outlines and their metrics remain byte-for-byte intact.
    """
    for filename in OPTIMA_FILES:
        path = ROOT / "public" / "fonts" / filename
        font = TTFont(path, recalcTimestamp=False)
        changed = False
        for table in font["cmap"].tables:
            if hasattr(table, "cmap"):
                safe = {cp: name for cp, name in table.cmap.items() if 0x20 <= cp <= 0x7E}
                changed = changed or safe != table.cmap
                table.cmap = safe
        if changed:
            font.save(path)
            print(f"Restricted unsafe legacy mapping: {filename}")
        font.close()


def audit():
    css = (ROOT / "src" / "index.css").read_text(encoding="utf-8")
    faces = {}
    for block in re.findall(r"@font-face\s*\{([^}]+)\}", css):
        family = re.search(r"font-family:\s*['\"]([^'\"]+)", block).group(1)
        urls = re.findall(r"url\(['\"]([^'\"]+)['\"]\)", block)
        source = next((url for url in urls if (ROOT / "public" / url.lstrip("/")).exists()), None)
        if source is None:
            raise ValueError(f"No available source for {family}: {urls}")
        path = ROOT / "public" / source.lstrip("/")
        font = TTFont(path, recalcTimestamp=False)
        glyphs = font.getGlyphSet()
        supported = set()
        empty = []
        for cp, name in (font.getBestCmap() or {}).items():
            if invisible(cp):
                supported.add(cp)
                continue
            pen = DecomposingRecordingPen(glyphs)
            glyphs[name].draw(pen)
            if pen.value:
                supported.add(cp)
            else:
                empty.append(cp)
        faces[family] = {
            "source": source,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "ranges": ranges(supported),
            "emptyGlyphs": sorted(empty),
            "samplesMissing": {
                label: "".join(dict.fromkeys(c for c in sample if not invisible(ord(c)) and ord(c) not in supported))
                for label, sample in SAMPLES.items()
            },
        }
        font.close()
    return {"samples": SAMPLES, "faces": faces}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify generated coverage is current")
    parser.add_argument("--repair-optima", action="store_true", help="Remove unsafe non-ASCII Optima mappings")
    args = parser.parse_args()
    if args.check and args.repair_optima:
        parser.error("--check cannot be combined with --repair-optima")
    logging.getLogger("fontTools").setLevel(logging.ERROR)
    if args.repair_optima:
        repair_optima()
    report = audit()
    # Compact lines keep generated coverage small while preserving reviewable entries.
    content = "// Generated by scripts/audit-fonts.py; do not edit by hand.\nexport default " + json.dumps(report, ensure_ascii=False, separators=(",", ":")) + ";\n"
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            raise SystemExit("Font coverage is stale. Run python scripts/audit-fonts.py")
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    faces = report["faces"]
    gaps = {name: face["samplesMissing"]["customerWording"] for name, face in faces.items() if face["samplesMissing"]["customerWording"]}
    print(f"Audited {len(faces)} browser faces; {len(faces) - len(gaps)} cover the full customer wording without fallback.")
    for name, missing in gaps.items():
        print(f"  {name}: " + " ".join(f"U+{ord(c):04X}" for c in missing))


if __name__ == "__main__":
    main()
