name = "customerfontselection-worker"
main = "src/index.js"

account_id = "4a97503a655eeb0db6059cf95e5a48cb"
workers_dev = true

compatibility_date = "2025-06-12"

[[r2_buckets]]
binding = "arch-font-uploads"           # This name must match what your Worker script uses
bucket_name = "arch-worker"
